### ISSUE TITLE
Crash when going to video settings

### ISSUE THREAD

**Issue by CaptConrad** [Nolij/Zume#20] opened 2024-06-08 23:02 UTC
![image](https://github.com/Nolij/Zume/assets/106116567/f03d1e81-21cf-4ea2-88e9-64a108053658)
[crash-2024-06-08_19.00.20-client.txt](https://github.com/user-attachments/files/15749836/crash-2024-06-08_19.00.20-client.txt)

**Comment by Nolij** [comment] 2024-06-08 23:14
Cannot reproduce. Does it happen consistently? Can you send the whole log so I can see if any errors occurred on launch?

**Comment by Nolij** [comment] 2024-06-08 23:22
Nevermind, I found the cause. It will be addressed in 1.0.0. For now remove Forgified Fabric API. You aren't using Connector, so you shouldn't need it. Forgified Fabric API causes this crash if Connector is not also present. If you install Connector you should be able to use Forgified Fabric API without issues.

**Comment by CaptConrad** [comment] 2024-06-08 23:38
> Nevermind, I found the cause. It will be addressed in 1.0.0. For now remove Forgified Fabric API. You aren't using Connector, so you shouldn't need it. Forgified Fabric API causes this crash if Connector is not also present. If you install Connector you should be able to use Forgified Fabric API without issues.

Disabling Forgified fixed the problem. Thank you.

**Comment by Nolij** [comment] 2024-06-08 23:42
Fixed as of [1.0.0-dev.8](https://github.com/Nolij/Zume/releases/tag/release%2F1.0.0-dev.8) (will be released as part of 1.0.0).

**Closed** 2024-06-15 20:12 UTC
Labels: bug
